// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_dear_citizen = "CgkI89vXu_0REAIQBA"; // <GPGSID>
        public const string achievement_where_is_my_prize = "CgkI89vXu_0REAIQCA"; // <GPGSID>
        public const string achievement_arefree_resident = "CgkI89vXu_0REAIQAw"; // <GPGSID>
        public const string achievement_shark_business = "CgkI89vXu_0REAIQBQ"; // <GPGSID>
        public const string achievement_newbie = "CgkI89vXu_0REAIQAg"; // <GPGSID>
        public const string leaderboard_leaderboard = "CgkI89vXu_0REAIQAA"; // <GPGSID>
        public const string achievement_get_ready = "CgkI89vXu_0REAIQAQ"; // <GPGSID>
        public const string achievement_business_man = "CgkI89vXu_0REAIQCQ"; // <GPGSID>
        public const string achievement_hard_worker = "CgkI89vXu_0REAIQBw"; // <GPGSID>
        public const string achievement_millionaire = "CgkI89vXu_0REAIQBg"; // <GPGSID>
        public const string achievement_influential_personality = "CgkI89vXu_0REAIQCg"; // <GPGSID>

}

